### ISSUE TITLE
[Bug] Cannot invoke "net.minecraft.class_239.method_17783()" because "trace" is null

### ISSUE THREAD

**Issue by Earthcomputer** [plusls/MasaGadget#101]
### Minecraft Version

1.20.1

### MasaGadget Version

3.2.318 67ab5b4-stable

### Description

Crash happens commonly when logging in with 1.20.1 with tweakeroo.

Tweakeroo's `RayTraceUtils.getRayTraceFromEntity` is marked `@Nonnull`. `RenderUtils` uses this method to get `trace`, but MasaGadgets redirects this to a cached version, which is nullable. This caused the crash.

Possible fix is to use `BlockHitResult.createMissed(Vec3d.ZERO, Direction.UP, BlockPos.ORIGIN);` instead of null, which is what `RayTraceUtils.getRayTraceFromEntity` uses for misses.

### To Reproduce

Not sure exactly, it seems to happen commonly though

### Expected behavior

No crash

### Log

https://mclo.gs/KMDPIk7

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Fix in 877ab5b should be worked.
