### ISSUE TITLE
[Feature Request] 将两个默认开启的功能设置为关闭

### ISSUE THREAD

**Issue by snpdzk** [plusls/MasaGadget#102]
### What new features do you want?

将 渲染村民绑定床 和 渲染村民绑定工作方块 这两个功能默认设置为关。最近总有人问村民头上的蓝线和红线是什么东西

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Hendrix-Shen** [comment]
此问题已在 dd10d03 中修改。如果急需使用，请在 GitHub Actions 中获取最新构建。
