### ISSUE TITLE
[Bug] 服务器中，村民补货一直显示 ok，本地单人正常显示时间。

### ISSUE THREAD

**Issue by Immortal-Sty** [plusls/MasaGadget#111]
### Minecraft Version

1.19.4

### MasaGadget Version

3.2.334+08c8f70-stable

### Description

服务器中，村民补货一直显示 ok，本地单人正常显示时间。

### To Reproduce

在服务器中，进入 MasaGadget 设置中开启“渲染村民交易补货冷却”，然后与村民交易，村民身上的时间显示依然是“ok”。

### Expected behavior

预期本来应该显示村民交易补货冷却时间。

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
参考 #97
