### ISSUE TITLE
[Bug] 预览村民导致崩溃

### ISSUE THREAD

**Issue by jfglzs** [plusls/MasaGadget#113]
### Minecraft Version

1.21

### MasaGadget Version

4.0.344

### Description

使用 预览功能预览村民时导致游戏崩溃

### To Reproduce

加入服务器（带有有servux）1.21
右键点击村民后
按alt 并且鼠标指针面向村民
预览 然后crashed
(tk是sakura的20.999-sakura15)

### Log

[crash-2024-07-15_00.36.11-client.txt](https://github.com/user-attachments/files/16228128/crash-2024-07-15_00.36.11-client.txt)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
试一下这个版本 [4.0.346-beta](https://github.com/plusls/MasaGadget/actions/runs/9932570122)

**Comment by jfglzs** [comment]
> 试一下这个版本 [4.0.346-beta](https://github.com/plusls/MasaGadget/actions/runs/9932570122)

好了 可以预览了

**Comment by jfglzs** [comment]
> > 试一下这个版本 [4.0.346-beta](https://github.com/plusls/MasaGadget/actions/runs/9932570122)
> 
> 好了 可以预览了

但是还是不能从服务端 拿到NBT数据 得用TIS的选项 或者 PCA同步
但是腐竹没开 （servux）也不行

**Comment by Hendrix-Shen** [comment]
所有同步问题要等到 PCA 同步协议重写后修复，现在需要把其他模组送上 1.21
