### ISSUE TITLE
[Bug] 翻译显示错误，设置框不显示

### ISSUE THREAD

**Issue by esuity** [plusls/MasaGadget#114]
### Minecraft Version

1.20.1

### MasaGadget Version

MasaGadget-mc1.20.1-fabric-4.0.344-stable

### Description

翻译失效，masa模组设置框不显示

### To Reproduce

1.打开masa模组的设置界面
2.观察到选择设置框消失
3.开启minihud显示
4.观察到未翻译

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by esuity** [comment]
好像是magiclib的问题？

**Comment by Hendrix-Shen** [comment]
MasaGadget 4.0 开始所有选项默认值均为原版行为，需要手动开启对应选项功能才会生效，需要注意的是 快捷切换栏设置后需要重新打开界面刷新
