### ISSUE TITLE
[Bug] 容器预览界面BUG

### ISSUE THREAD

**Issue by qwq10000** [plusls/MasaGadget#115]
### Minecraft Version

1.21

### MasaGadget Version

4.0.347

### Description

容器预览玩家和生物界面错位

### To Reproduce

![image](https://github.com/user-attachments/assets/87b4112c-89b7-43ea-ac48-ccfb1f6e5eb5)
![image](https://github.com/user-attachments/assets/390665be-8f80-4cea-94ef-14a037fa7604)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请将 minihud 中的容器预览快捷键设置为空。即使不安装 MasaGadget，MC 1.21+ 中 Tweakeroo 和 MiniHud 容器预览也会发生渲染冲突
