### ISSUE TITLE
[Bug] 显示原始的选项配置名导致游戏崩溃

### ISSUE THREAD

**Issue by acaciachan** [plusls/MasaGadget#117]
### Minecraft Version

1.15.2

### MasaGadget Version

最新

### Description

[crash-2024-07-21_09.06.08-client.txt](https://github.com/user-attachments/files/16322732/crash-2024-07-21_09.06.08-client.txt)

### To Reproduce

开启"显示原始的配置选项名"之后就崩溃了，重启之后因为配置文件保留着一旦点开设置继续崩溃
另外无论masagadget里面的这个功能开关之后，tweakermore都无法受影响，而且即使masagadget里面的这个重复功能关掉，tweakermore里的这个功能也无法起作用，同样版本号的最新版，1.20.4没有i18那个配置，1.15.2和1.20.4似乎选项配置是不同步的

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
试一下这个版本 [4.0.354-beta](https://github.com/plusls/MasaGadget/actions/runs/10026040496)

**Comment by Hendrix-Shen** [comment]
其他问题：
- TweakerMore 的选项标签是不能关闭自身的，与 MasaGadget 无关
- 部分配置存在约束条件，在 MagicLib 中启用 `调试模式` 并关闭 `隐藏不可用配置` 即可看到被隐藏的配置及其约束条件
