### ISSUE TITLE
[Bug] 游戏似乎因为实体minecraft:zombie_villager(28.53,18.031.75)出现了问题。

### ISSUE THREAD

**Issue by paulxjz** [plusls/MasaGadget#122]
### Minecraft Version

1.21

### MasaGadget Version

MasaGadget-mc1.21-fabric-4.0.364-stable

### Description

![Quicker_20240803_171332](https://github.com/user-attachments/assets/1ad7ea5b-9c0d-440c-8455-ab3d28506c06)

### To Reproduce

从MasaGadget-mc1.21-fabric-4.0.355-stable更新到MasaGadget-mc1.21-fabric-4.0.364-stable，一打开进入世界就闪退

### Log

[错误报告-2024-8-3_17.13.46.zip](https://github.com/user-attachments/files/16478908/-2024-8-3_17.13.46.zip)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请更新 MagicLib

**Comment by paulxjz** [comment]
可以了，感谢修复
