### ISSUE TITLE
1.20.4版本下不能生成僵尸村民实体的问题

### ISSUE THREAD

**Issue by 50vvv** [plusls/MasaGadget#123]
### Minecraft Version

1.20.4

### MasaGadget Version

4.0.364

### Description

最新的4.0.364版本中只要生产僵尸村民实体就会导致游戏崩溃
需要崩溃报告和更多数据可以联系我

### To Reproduce

加载上最新版的masagadget，开启任何游戏，放置僵尸村民

### Expected behavior

尽快解决(●'◡'●)

### Log

[错误报告-2024-8-3_21.29.10.zip](https://github.com/user-attachments/files/16480943/-2024-8-3_21.29.10.zip)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
与 #122 重复
