### ISSUE TITLE
[Bug] MasaGadget-mc1.21-fabric-4.0.364遇到僵尸村民会立刻闪退。

### ISSUE THREAD

**Issue by MOFUMOOFU** [plusls/MasaGadget#124]
### Minecraft Version

1.21

### MasaGadget Version

4.0.364

### Description

4.0.364版本遇到**僵尸村民**游戏会立刻闪退。
但是4.0.355版本就不会。
测试只有{fabric api、magiclib、malilib、masa gadget}的情况下也会触发闪退。
![屏幕截图 2024-08-04 204040](https://github.com/user-attachments/assets/85e0e27d-4d74-4909-b633-165259ed0742)

### To Reproduce

在单机或在线模式下遇到或使用生物蛋生成僵尸村民会立刻崩溃。

### Log

[minecraft-exported-crash-info-2024-08-04T20-43-57.zip](https://github.com/user-attachments/files/16487594/minecraft-exported-crash-info-2024-08-04T20-43-57.zip)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by MOFUMOOFU** [comment]
这是其他依赖的版本：
fabric-api-0.100.8+1.21
MagicLib-mc1.21.0-fabric-0.8.576-stable
malilib-fabric-1.21-0.19.999-sakura.4
MasaGadget-mc1.21-fabric-4.0.364-stable

**Comment by Hendrix-Shen** [comment]
与 #122 重复
