### ISSUE TITLE
[Bug] 1.20.1在特定情况下客户端崩溃

### ISSUE THREAD

**Issue by LLovelyMrzheng** [plusls/MasaGadget#125]
### Minecraft Version

1.20.1

### MasaGadget Version

4.0.364

### Description

进入服务器后游戏崩溃，单人模式正常

### To Reproduce

只要一进我自己的服务器就崩溃，看日志好像是跟一个僵尸村民的实体有关，我也看不懂T-T

### Log

[crash-2024-08-10_19.08.58-client.txt](https://github.com/user-attachments/files/16569325/crash-2024-08-10_19.08.58-client.txt)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
与 Hendrix-Shen/MagicLib#90 有关，尝试降级 MagicLib 或将 MasaGadget 升级到 [4.0.366-beta](https://github.com/plusls/MasaGadget/actions/runs/10321993741)
