### ISSUE TITLE
[Bug] 遇到僵尸村民立即闪退 MagicLib是最新的MagicLib-mc1.21.1-fabric-0.8.609-beta MasaGadget是最新的MasaGadget-mc1.21-fabric-4.0.364-stable

### ISSUE THREAD

**Issue by zhjc2021** [plusls/MasaGadget#128]
### Minecraft Version

1.21.1

### MasaGadget Version

MasaGadget-mc1.21-fabric-4.0.364-stable

### Description

[crash-2024-08-30_14.27.43-client.txt](https://github.com/user-attachments/files/16812759/crash-2024-08-30_14.27.43-client.txt)

MagicLib和MasaGadget都是最新版本

### To Reproduce

召唤出或者遇到僵尸村民立刻崩溃

### Latest CI build tested

- [x] I confirm that this problem still exists with the latest CI build.

**Comment by zhjc2021** [comment]
bump

**Comment by vocaloidkiss** [comment]
我在MagicLib-mc1.21.0-fabric-0.8.596-beta也遇到了这个问题

**Comment by vocaloidkiss** [comment]
@Hendrix-Shen

**Comment by Arusk-i** [comment]
同问，这个bug大概什么时候能修复呢

**Comment by vocaloidkiss** [comment]
@Arusk-i 用最新版masagadget就好了，在action里
