### ISSUE TITLE
村民交易预渲染的想法

### ISSUE THREAD

**Issue by Shao-JinEi** [plusls/MasaGadget#14]
首先\plusls/
==
在看到图书管理员交易第一层附魔书渲染功能之后，小伙伴们看到了之后都很喜欢，包括我~~（逃~~

>我们一致认为这个功能是非常好用的

在感叹之后，我们又想到了更多有意思的想法，由我来提交一下issues

对于第一层附魔书交易的建议
==
我们觉得，如果这个功能中能够**显示**附魔书的**价格**就更好了w!

其实我的想法是这样的，不光显示附魔书的价格，而且要是该价格是当前最高附魔的最低价，用<font color=#800080>紫色</font>(~~或者用其它比较显眼的颜色~~)显示就更好力！

从wiki了解得知附魔书交易拥有最低价的——>>[注释8.0wiki链接](https://wiki.biligame.com/mc/%E4%BA%A4%E6%98%93#cite_note-enchanted-book-8)
![交易最低价](https://github.com/Shao-JinEi/pocket/blob/main/%E4%BA%A4%E6%98%93%E7%9A%84%E6%9C%80%E4%BD%8E%E4%BB%B7.png)

就是说**锋利V**的最低价是17，**经验修补**由于是**宝藏附魔**最低价是10，在该最低价的时候，渲染出来的颜色与众不同www

------
对于第一层交易渲染的其它建议
==
我们可以看到，其他职业的村民在第一层交易也是随机的，比如农民和屠户

  - **农民**的第一层交易随机出现两种交易——四种农作物和一种绿宝石交换物：小麦、土豆、胡萝卜、甜菜根和面包。
![农民](https://patchwiki.biligame.com/images/mc/thumb/e/ea/kfj8mjf7qjpli2f6s2p80g7psjokyv1.png/156px-Plains_Farmer.png) ![小麦](https://wiki.biligame.com/mc/%E5%B0%8F%E9%BA%A6#/media/File:Wheat_JE2_BE2.png) ![土豆](https://wiki.biligame.com/mc/%E9%A9%AC%E9%93%83%E8%96%AF#/media/File:Potato_JE3_BE2.png)  ![胡萝卜](https://wiki.biligame.com/mc/%E8%83%A1%E8%90%9D%E5%8D%9C#/media/File:Carrot_JE3_BE2.png) ![甜菜](https://wiki.biligame.com/mc/%E7%94%9C%E8%8F%9C%E6%A0%B9#/media/File:Beetroot_JE2_BE2.png) ![面包](https://wiki.biligame.com/mc/%E9%9D%A2%E5%8C%85#/media/File:Bread_JE3_BE3.png)

  - **屠户**的第一层交易随机出现两种交易——三种肉类和一种绿宝石交换物：生鸡肉、生兔肉、生猪排和兔肉煲。
![屠户](https://patchwiki.biligame.com/images/mc/thumb/f/ff/7klw8h1divj3zk633cpk88vsane1wjs.png/119px-Plains_Butcher.png) ![生鸡肉](https://wiki.biligame.com/mc/%E7%94%9F%E9%B8%A1%E8%82%89#/media/File:Raw_Chicken_JE3_BE3.png) ![生兔肉](https://wiki.biligame.com/mc/%E7%94%9F%E5%85%94%E8%82%89#/media/File:Raw_Rabbit_JE3_BE2.png) ![生猪排](https://wiki.biligame.com/mc/%E7%94%9F%E7%8C%AA%E6%8E%92#/media/File:Raw_Porkchop_JE2_BE2.png) ![兔肉煲](https://wiki.biligame.com/mc/%E5%85%94%E8%82%89%E7%85%B2#/media/File:Rabbit_Stew_Revision_2.png)

***想法就是能够在远处便能分辨出来那个村民拥有相应的交易，能够更加方便的帮助到小伙伴们的生存w***

我认为可以单独开一个功能大类——**村民交易预渲染(renderTradePreview)**

下面加几个小类别，包括**渲染村民交易的第一本附魔书(renderTradeEnchantedBook)**之类的

我也知道写mod很难，但是我们会来加油打气嗒\plusls/

**Comment by plusls** [comment]
如果是非附魔书的话我可能会直接考虑渲染出图标，但是这个功能主要是为了方便刷交易的，如果是不刷交易的场景，往往可以在对应村民的位置放对应的展示框，直接看出来

而且，其实现在 mod 对着村民使用容器预览是可以看到村民交易的产物的，你可以试试，只是没显示价格而已

关于显示价格和低价高价区间，这个提议确实有意义，但是有一个问题，如果要显示价格我有点担心会不会导致文本太长显示不全，毕竟刁民交易所有多小大家都是知道的，到时候遮住了文本就很难顶了（除非渲染2行）

自动刷交易其实是有打算做的，但是具体怎么设计与玩家的交互还在考虑中（咕咕咕

**Comment by Shao-JinEi** [comment]
不是附魔书直接渲染图标妙啊（
图标纵向排列的那种）
价格可以考虑下换行，如果不显示价格的话，可以考虑下最低价格换成另一个**颜色**
tql

**Comment by plusls** [comment]
主要是现在对着村民用容器预览本身就可以显示出所有交易，所以渲染别的交易是否有必要呢（因为我个人感觉是没必要的

毕竟容器预览本身就能结合 freecamera 使用，砍掉工作方块再放一个，按一下预览键就能看到交易了，至于寻找哪个村民卖什么的问题，我个人倾向于在游戏内使用展示框或者特定方块来进行指示

**Comment by Shao-JinEi** [comment]
建议而已hhh
具体怎么修改看你的意愿（逃

**Comment by plusls** [comment]
![-683a4e3d78b7e508 png](https://user-images.githubusercontent.com/23459592/133097647-50ae535c-8ec3-4564-9d38-c455d68981b4.jpg)
预期效果

**Comment by Shao-JinEi** [comment]
其实我有个颜色分级的概念，比较弱的附魔书渲染字体可以变成**黑色**的，比如说最低级次的附魔毕竟不是很好的附魔，具体是什么可以连看都不用看，根据颜色直接判断，我们有些玩家在大量的去刷交易的时候如果仔细看字的话可能会出现**视觉疲劳**的现象，如果用一定的颜色来提示，那么可能有一定程度的缓解(逃

**Comment by plusls** [comment]
那颜色分级确实已经做了的，不过价格确实有做颜色的打算（咕咕咕

**Comment by Shao-JinEi** [comment]
tql,拭目以待，其实不用太着急的hh，其实我还有很多奇妙点子，但是碍于自己的能力实现不了，只能摆脱你了）
