### ISSUE TITLE
低版本更新

### ISSUE THREAD

**Issue by Q3213522398** [plusls/MasaGadget#15]
大佬会考虑更新低版本吗，1.15的菜鸡也行用上qwq

**Comment by plusls** [comment]
因为116到115变动挺大的，如果要向后兼容挺麻烦的，这边建议1.16的端配合上via或者 multiconnect去连低版本

**Comment by Q3213522398** [comment]
嗯嗯，好的吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月13日(星期一) 晚上10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [plusls/MasaGadget] 低版本更新 (#15)





 
因为116到115变动挺大的，如果要向后兼容挺麻烦的，这边建议1.16的端配合上via或者 multiconnect去连低版本
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by plusls** [comment]
也许有空时会尝试去做适配，但是近期应该没有想法？（但是pca的支持范围是1.14-1.18的，所以服务器是没问题的）

**Comment by Q3213522398** [comment]
okk(awa




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月13日(星期一) 晚上10:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [plusls/MasaGadget] 低版本更新 (#15)





 
也许有空时会尝试去做适配，但是近期应该没有想法？（但是pca的支持范围是1.14-1.18的，所以服务器是没问题的）
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Q3213522398** [comment]
okk

**Comment by Q3213522398** [comment]
releases里面没找到，文件要到哪里下载awa?

**Comment by plusls** [comment]
> releases里面没找到，文件要到哪里下载awa?

https://github.com/plusls/MasaGadget/actions/runs/1237288199
以后这种未 release 的 build 都可以从 action 找

**Comment by Q3213522398** [comment]
哦哦，懂了

**Comment by Q3213522398** [comment]
这个如果要在服务器里面能用的话，是不是也要把这个模组放到服务器的mods文件夹里面awa

**Comment by Hendrix-Shen** [comment]
> 这个如果要在服务器里面能用的话，是不是也要把这个模组放到服务器的mods文件夹里面awa

服务端侧是由 [PCA](https://github.com/plusls/plusls-carpet-addition) 来支持的，安装对应版本的 PCA 并启用 `pcaSyncProtocol`

**Comment by Q3213522398** [comment]
okk
