### ISSUE TITLE
在服务器上面结果不正确

### ISSUE THREAD

**Issue by liuyujielol** [plusls/MasaGadget#17]
![image](https://user-images.githubusercontent.com/19249377/135796240-8caee068-a4ff-42e8-a38d-cf4bde8c4395.png)
![image](https://user-images.githubusercontent.com/19249377/135796268-04d0e736-51ab-4b40-ae8d-8b34398833f7.png)
服务器上面的mod：
![image](https://user-images.githubusercontent.com/19249377/135796324-b964cc03-ce61-41e9-bce8-c203497b4d14.png)

**Comment by plusls** [comment]
服务器不需要装masagadget，同时服务器需要打开 /carpet pcaSyncProtocol

**Comment by liuyujielol** [comment]
也就是说只需要malilib和pca然后打开pcaSyncProtocol就可以了吗

**Comment by plusls** [comment]
服务器也不需要malilib

**Comment by liuyujielol** [comment]
ok，谢谢
