### ISSUE TITLE
Tweakeroo FreeCamera Inventory Viewing Doesn't Work Properly

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [plusls/MasaGadget#2]
**Expected behaviour:**

I enter free camera mode and can open containers (with this mod)

**Actual behaviour:**

I enter free camera mode, but I can open only a single container, which is the one which my player's body is looking at.

**Comment by plusls** [comment]
When you enter free camera mode , you can use inventory preview, but you can't open containers....

**Comment by DragonEggBedrockBreaking** [comment]
> When you enter free camera mode , you can use inventory preview, but you can't open containers, if your containers means open chest and take somthing.

I know, but I cannot preview the inventories either. I right click on the chest to do it, so do i need to something else? And do I need to enable a new tweakeroo feature for it to work?

**Comment by plusls** [comment]
> > When you enter free camera mode , you can use inventory preview, but you can't open containers, if your containers means open chest and take somthing.
> 
> I know, but I cannot preview the inventories either. I right click on the chest to do it, so do i need to something else? And do I need to enable a new tweakeroo feature for it to work?

You need enable inventoryPreview

![image](https://user-images.githubusercontent.com/23459592/111657614-91cab000-8846-11eb-8bbd-c49c99966e5d.png)

![image](https://user-images.githubusercontent.com/23459592/111657659-9becae80-8846-11eb-8a06-34542921602f.png)

**Comment by DragonEggBedrockBreaking** [comment]
> You need enable inventoryPreview
> 
> ![image](https://user-images.githubusercontent.com/23459592/111657614-91cab000-8846-11eb-8bbd-c49c99966e5d.png)
> 
> ![image](https://user-images.githubusercontent.com/23459592/111657659-9becae80-8846-11eb-8a06-34542921602f.png)

Ah, OK.
