### ISSUE TITLE
添加对 ExtraPlayerRenderer 的切换配置界面下拉菜单支持

### ISSUE THREAD

**Issue by SkyNetX007** [plusls/MasaGadget#26]
添加对同样基于 malilib 的 [ExtraPlayerRenderer](https://github.com/LucunJi/ExtraPlayerRenderer) 的快速切换配置界面下拉菜单支持。

**Comment by plusls** [comment]
有空看看，但是理论上用了malilib都支持的

**Comment by SkyNetX007** [comment]
实际上界面里已经有 masa gadget 的下拉框了，只是没有指向 extraplayerrender 的选项

**Comment by plusls** [comment]
这个是因为 extraplayerrender 不支持 modmenu，我发了个pr，等作者合并吧

**Comment by plusls** [comment]
[ExtraPlayerRenderer-1.18.1-2.1.1.jar.tar.gz](https://github.com/plusls/MasaGadget/files/7745284/ExtraPlayerRenderer-1.18.1-2.1.1.jar.tar.gz)
发了个1.18.1的，将就用吧
