### ISSUE TITLE
容器预览格子信息错位

### ISSUE THREAD

**Issue by Dream4Leo** [plusls/MasaGadget#27]
minecraft version: 1.17.1
masagadget version: 2.0.6
tweakeroo version: 0.10.0
渲染分辨率：1280x720
预览箱子、漏斗等一级容器界面时，使用鼠标滚轮选中格子，渲染的信息位置错误。在窗口模式和全屏模式下均有此问题。
![image](https://user-images.githubusercontent.com/48596730/146662350-9077c5e2-8208-4d41-a134-05e6854ae587.png)
预览箱子中的潜影盒时没有错位问题。

**Comment by plusls** [comment]
试试 github action 的版本？应该修了

**Comment by Dream4Leo** [comment]
使用github action中的2.0.7-beta.b51c38f版本后，问题解决。
