### ISSUE TITLE
Crash when try to easyplace stair

### ISSUE THREAD

**Issue by LuxuriaGK** [plusls/MasaGadget#28]
Set wrong value for stairs facing
Crash in short: java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to down on Block{minecraft:deepslate_tile_stairs}, it is not an allowed value

full crash log at below
[crash-2021-12-27_21.07.02-client.txt](https://github.com/plusls/MasaGadget/files/7780312/crash-2021-12-27_21.07.02-client.txt)

**Comment by LuxuriaGK** [comment]
seems like carpet-extra accurateBlockPlacement also will cause the same problem, maybe it's something cause by litematica

**Comment by plusls** [comment]
try easy placement protocol v2?

**Comment by LuxuriaGK** [comment]
ok, it works so well with protocol v2
