### ISSUE TITLE
chest preview crashes the game on 1.18?

### ISSUE THREAD

**Issue by KrisCris** [plusls/MasaGadget#29]
https://github.com/maruohon/tweakeroo/issues/308

**Comment by KrisCris** [comment]
MasaGadget-fabric-21w41a-2.0.6.jar

**Comment by Hendrix-Shen** [comment]
Try using the latest CI build.
https://github.com/plusls/MasaGadget/actions/runs/1634867749

**Comment by KrisCris** [comment]
Thanks, the problem is resolved!
