### ISSUE TITLE
问题反馈 使用容器预览导致游戏崩溃

### ISSUE THREAD

**Issue by YehowahLiu** [plusls/MasaGadget#30]
### 问题描述
在更新tweakroo后，使用容器预览会导致游戏崩溃，将masagadget禁用后恢复正常，预计可能为tweakroo的新版本变动导致的masagadget不适配

### 版本信息
mc 1.17.1
tweakroo 0.11.0
masagadget 2.0.6 

### 其他
报错日志 https://paste.ee/p/EP72S

**Comment by Hendrix-Shen** [comment]
感谢您的报告！
是否使用最新 CI 构建 https://github.com/plusls/MasaGadget/actions/runs/1512923306 ，若问题依然存在，请上传最新构建的相关日志。

**Comment by YehowahLiu** [comment]
最新构建无此问题，感谢！
