### ISSUE TITLE
[Bug] Game crash

### ISSUE THREAD

**Issue by kai128** [plusls/MasaGadget#32]
### Minecraft Version

1.18.1

### MasaGadget Version

2.0.6

### Description

The game crash when my head is inside lava meanwhile my leg in in the water
![b](https://user-images.githubusercontent.com/78844199/148369116-7a18ede1-58ed-495d-87c7-50ece209c7c6.png)

### To Reproduce

Just put your leg inside water and put your head inside lava
![a](https://user-images.githubusercontent.com/78844199/148368598-504cc157-c11e-4196-9498-0f65f9dfde9e.png)
a

### Latest CI build tested

- [x] I confirm that this problem still exists with the latest CI build.

**Comment by plusls** [comment]
any log?

**Comment by Hendrix-Shen** [comment]
Thank you for your report.
Try using the latest CI build. https://github.com/plusls/MasaGadget/actions/runs/1660665591 If the problem persists, please upload the latest log here.

**Comment by kai128** [comment]
> any log?
[crash-2022-01-07_15.23.31-client.txt](https://github.com/plusls/MasaGadget/files/7827205/crash-2022-01-07_15.23.31-client.txt)
