### ISSUE TITLE
在界面尺寸较低的情况下启用「显示原始的配置选项名」的时候，原始配置选项名非常模糊

### ISSUE THREAD

**Issue by Cubik65536** [plusls/MasaGadget#36]
### Minecraft 版本：
Minecraft Java Edition 1.18.1

### MasaGadget 版本：
MasaGadget-1.18.1-2.0.8

### 描述：
在使用 iris-mc1.18.1-1.2.0-pre，界面尺寸较低的情况下启用「显示原始的配置选项名」的时候，原始配置选项名非常模糊。

### 截图：
<img width="1956" alt="iShot2022-02-13 14 35 31" src="https://user-images.githubusercontent.com/72877496/153772818-00158adf-2424-4f28-961a-433db3013875.png">

**Comment by plusls** [comment]
这个我好像也没什么办法，不能把界面调大一点嘛（毕竟底层渲染都用的masa的代码，动的话太痛苦了

**Comment by Cubik65536** [comment]
> 这个我好像也没什么办法，不能把界面调大一点嘛（毕竟底层渲染都用的masa的代码，动的话太痛苦了

由于我屏幕本身分辨率特殊（应该是），所以调整之后会让其他ui（尤其是mc自己的物品栏，菜单等内容）特别大。目前方案是调整设置的时候临时把缩放调大，由于调整不频繁，这还算是一个可用方案。

**Comment by plusls** [comment]
没办法 太蔡了写不来渲染，只能等 masa 修了2333

**Comment by Cubik65536** [comment]
> 没办法 太蔡了写不来渲染，只能等 masa 修了2333

那目前 masa 那边有没有相关 issue？还是还没有人反馈

**Comment by plusls** [comment]
> > 没办法 太蔡了写不来渲染，只能等 masa 修了2333
> 
> 那目前 masa 那边有没有相关 issue？还是还没有人反馈

主要还是我最近比较忙，渲染这块的代码我确实不太懂（x
如果有空倒是可以试试修它

**Comment by Cubik65536** [comment]
> > > 没办法 太蔡了写不来渲染，只能等 masa 修了2333
> > 
> > 
> > 那目前 masa 那边有没有相关 issue？还是还没有人反馈
> 
> 主要还是我最近比较忙，渲染这块的代码我确实不太懂（x 如果有空倒是可以试试修它

其实我本来打算去 masa 那边提交 issue 的，但是我发现我也不知道该到哪个 repo 我也不知道怎么描述这个渲染问题，就麻烦 dalao 了（x

**Comment by Cubik65536** [comment]
> 要想修这玩意估计得把高清字体从低版本或者 forge 弄来，有点裂开

az，想帮忙也帮不上啊（捂脸

**Comment by plusls** [comment]
想不到啥特别好的方案，我现在提供了一个字体大小的设置（指下面小字的字体大小），手动调节将就一下？

**Comment by Cubik65536** [comment]
> 想不到啥特别好的方案，我现在提供了一个字体大小的设置（指下面小字的字体大小），手动调节将就一下？

反正现在也是缩放调来调去将就，能调一次不再调也行
