### ISSUE TITLE
[Question] 渲染不正确

### ISSUE THREAD

**Issue by laoyali** [plusls/MasaGadget#38]
### Question Type

Usages

### Description

我的服务器用的是paper核心
村民交易渲染并不能正确显示
![image](https://user-images.githubusercontent.com/58849532/160370045-2d02c7ba-9f49-4adf-bffa-f1a04ba5a16d.png)
有解决办法吗大佬

**Comment by plusls** [comment]
因为这个需要服务器安装pca，目前pca并没有 paper 的版本，所以没啥办法（以后也许会有？
