### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Pi3tro88** [plusls/MasaGadget#39]
### Minecraft Version

1.18.2

### MasaGadget Version

2.0.9.1

### Description

with tweakeroo's inventory preview, when looking at a player's inventory it only shows a small part of the inventory (the armour and the main and off hand), the rest of the inventory seams in fact empty

### To Reproduce

target a player pressing your inventory preview key

### Expected behavior

you should see the rest of the inventory

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by plusls** [comment]
> 

If you want see other player's inventory, you need install plusls carpet addiition in server

**Comment by Pi3tro88** [comment]
oh yeah its installed

**Comment by Pi3tro88** [comment]
we can see tile entity inventory

**Comment by plusls** [comment]
you should enable `pcaSyncProtocol` and `pcaSyncPlayerEntity`

**Comment by Pi3tro88** [comment]
on the server?

**Comment by plusls** [comment]
> on the server?

yees

**Comment by Pi3tro88** [comment]
alright, thanks

**Comment by Pi3tro88** [comment]
just realised it was on ops instead of true lol
