### ISSUE TITLE
[Question] 如何使用“修复精准放置协议”？

### ISSUE THREAD

**Issue by solitary-sails** [plusls/MasaGadget#45]
### Question Type

Usages

### Description

请问启用修复精准放置协议这个功能后，在litematic的设置中应该选择哪一个协议版本？Auto就好还是某个特定的选择，我选择Auto时，栅栏门，比较器，楼梯可以精准放置但侦测器无效。

**Comment by solitary-sails** [comment]
补充：服务端安装了您的plusls-carpet-addition并启用了pcaSyncProtocol

**Comment by GJayun** [comment]
怎么解决的？
