### ISSUE TITLE
[Bug] Rendering issues when both Iris and Gadget are enabled

### ISSUE THREAD

**Issue by Labrador52** [plusls/MasaGadget#47]
### Minecraft Version

1.19

### MasaGadget Version

3.0.0

### Description

![javaw_DNcezqFqPW](https://user-images.githubusercontent.com/60187621/178408149-550d40bd-32e6-41e4-a1c0-3cfc733bcf9d.png)
如图所示，当我同时启用Iris与Gadget时，Gadget的渲染会直接跳过后方的实体（村民的脸），能用但逼死强迫症。
PS：图中的命名牌用于检测Iris是否也会影响命名牌的渲染方式，结果是命名牌依然按照原版的方式渲染，不会遮挡实体
As shown in the picture, when I enable Iris and gadget at the same time, the rendering of Gadget seems to become abnormal (although acceptable), which should not be expected.

### To Reproduce

只要同时启用Iris和Gadget似乎就会发生（我还没尝试仅启用Iris和Gadget）。
This problem seems to occur when I enable both Iris and Gadget

### Expected behavior

希望能修复成命名牌样式，或者给渲染层添加一些格式设置
I hope that when Iris and Gadget are enabled at the same time, the information of Gadget can be rendered in the same way as the name tag, rather than obscuring the entities behind

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by plusls** [comment]
这个是已知的问题，但是一直没空修，又不是不能用.jpg

主要是我太菜了，不太写的来渲染
