### ISSUE TITLE
[Bug] 已装magiclib-0.5.37的情况下，游戏无法打开。

### ISSUE THREAD

**Issue by bAdOoWindy** [plusls/MasaGadget#50]
### Minecraft Version

1.19.2

### MasaGadget Version

MasaGadget-1.19-3.0.0

### Description

装magiclib-0.5.31的话其他1.19.2的masa MOD无法启动

### To Reproduce

MOD列表
![图片](https://user-images.githubusercontent.com/4119845/184049816-93fdce7a-ec8d-41b7-ad75-2e5ceaae1c5a.png)
![图片](https://user-images.githubusercontent.com/4119845/184049865-7f7a756f-618b-4291-b5e8-34a3c7a1e13f.png)
![图片](https://user-images.githubusercontent.com/4119845/184049892-23565b71-66fa-4878-8241-f5851654282f.png)

### Log

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install magiclib-1_19, version 0.5.30 or later.
Unmet dependency listing:
	 - Mod 'Masa Gadget for 1.19' (masa_gadget_mod-1_19) 3.0.0 requires version 0.5.30 or later of magiclib-1_19, which is missing!
	 - Mod 'Oh My Minecraft Client for 1.19' (ommc-1_19) 0.5 requires version 0.5.30 or later of magiclib-1_19, which is missing!
	 - Mod 'Tinfoiled Cotton Client Commands' (cotton-client-commands) 1.1.0+1.15.2 requires any version between 1.14- (inclusive) and 1.16- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.14.4' (magiclib-1_14_4) 0.5.37 requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.15.2' (magiclib-1_15_2) 0.5.37 requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.16.5' (magiclib-1_16_5) 0.5.37 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.17.1' (magiclib-1_17_1) 0.5.37 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.18.2' (magiclib-1_18_2) 0.5.37 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.8+15-main requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.8+15-main requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.8+15-main requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.8+15-main requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc118) 0.4.8+15-main requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
MC 1.19.2 请使用 [3.0.0-beta+1bf6939](https://github.com/plusls/MasaGadget/suites/7754267568/artifacts/325704105)

**Comment by bAdOoWindy** [comment]
已经是MasaGadget-3.0.0-beta+1bf6939了，还是不行。日志如下

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Masa Gadget' (masa_gadget_mod) 3.0.0-beta+1bf6939 with any version that is compatible with:
		 - magiclib 0.5.37
Unmet dependency listing:
	 - Mod 'Masa Gadget' (masa_gadget_mod) 3.0.0-beta+1bf6939 requires version 0.5.38 or later of mod 'MagicLib' (magiclib), but only the wrong version is present: 0.5.37!
	 - Mod 'Tinfoiled Cotton Client Commands' (cotton-client-commands) 1.1.0+1.15.2 requires any version between 1.14- (inclusive) and 1.16- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.14.4' (magiclib-1_14_4) 0.5.37 requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.15.2' (magiclib-1_15_2) 0.5.37 requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.16.5' (magiclib-1_16_5) 0.5.37 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.17.1' (magiclib-1_17_1) 0.5.37 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.18.2' (magiclib-1_18_2) 0.5.37 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.14.4' (masa_gadget_mod-1_14_4) 3.0.0-beta+1bf6939 requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.15.2' (masa_gadget_mod-1_15_2) 3.0.0-beta+1bf6939 requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.16.5' (masa_gadget_mod-1_16_5) 3.0.0-beta+1bf6939 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.17.1' (masa_gadget_mod-1_17_1) 3.0.0-beta+1bf6939 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.18.2' (masa_gadget_mod-1_18_2) 3.0.0-beta+1bf6939 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Oh My Minecraft Client for 1.14.4' (ommc-1_14_4) 0.5-beta+657858c requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Oh My Minecraft Client for 1.15.2' (ommc-1_15_2) 0.5-beta+657858c requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Oh My Minecraft Client for 1.16.5' (ommc-1_16_5) 0.5-beta+657858c requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Oh My Minecraft Client for 1.17.1' (ommc-1_17_1) 0.5-beta+657858c requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Oh My Minecraft Client for 1.18.2' (ommc-1_18_2) 0.5-beta+657858c requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.8+15-main requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.8+15-main requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.8+15-main requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.8+15-main requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc118) 0.4.8+15-main requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Hendrix-Shen** [comment]
大意了，试一下这个版本 [3.0.0-beta+0d38417](https://github.com/plusls/MasaGadget/suites/7919009900/artifacts/337365588)
