### ISSUE TITLE
[Bug] 自动寻找最近的刷怪点 无法自动高亮坐标

### ISSUE THREAD

**Issue by HhiPyrene** [plusls/MasaGadget#53]
### Minecraft Version

1.19.2

### MasaGadget Version

3.0.0-beta+bc54082

### Description

使用该功能后自动发出的高亮指令直接发送至聊天而不能正常使用
![huge_2022-08-22_16 36 27_03](https://user-images.githubusercontent.com/111572269/185879149-9a720290-284c-4167-a8f6-91480ee044b6.png)

### To Reproduce

自动寻找最近的可刷怪地点

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
试一下这个版本 [3.2.293+c5807e6-beta](https://github.com/plusls/MasaGadget/suites/12045882016/artifacts/633407991)。

**Comment by HhiPyrene** [comment]
> 试一下这个版本 [3.2.293+c5807e6-beta](https://github.com/plusls/MasaGadget/suites/12045882016/artifacts/633407991)。

感谢，已解决

**Comment by HhiPyrene** [comment]
![huge_2023-04-08_12 57 40](https://user-images.githubusercontent.com/111572269/230703966-9fdea642-d529-42e8-9bd2-0caa93ead431.png)
还是不行，发现它会打出两个/
