### ISSUE TITLE
MasaGadget-3.0.0则可以进入游戏，但无游戏内选项

### ISSUE THREAD

**Issue by ALARM1NG** [plusls/MasaGadget#54]
### Minecraft Version

1.19.2

### MasaGadget Version

3.0.0

### Description

使用magiclib-0.6.185+3bd5dbb-beta为前置，若使用带有版本后缀的MASAGadget版本无法识别前置，使用MasaGadget-3.0.0则可以进入游戏，但无游戏内选项
![K4TIA1VZ49XXM)R2SBXQ)$3](https://user-images.githubusercontent.com/113773647/190854818-40cf3987-b793-4d81-9223-4f19f1189a75.png)
同时游戏内快捷键无法唤起

### To Reproduce

正常启动

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
使用的[3.0.0-beta+0d38417](https://github.com/plusls/MasaGadget/suites/7919009900/artifacts/337365588)版本？

**Comment by ALARM1NG** [comment]
解决了，多谢p老师
