### ISSUE TITLE
[Question] 无法在服务器里获取到村民交易信息

### ISSUE THREAD

**Issue by zero-OD** [plusls/MasaGadget#55]
### Question Type

Others

### Description

单人游玩正常，可是在服务器里无法获取，每次的重新进入服务器才能获取到，而且获取了后也一直是哪个，挖掉职业方块重新刷新，依旧显示原来的

**Comment by Hendrix-Shen** [comment]
多人游戏需要服务器安装 [PCA](https://github.com/plusls/plusls-carpet-addition) 并启用 `pcaSyncProtocol`。
目前有且仅有Fabric服务端可以安装PCA来确保同步，其他类型服务端没有支持计划。

**Comment by TjXySky** [comment]
> 多人游戏需要服务器安装 [PCA](https://github.com/plusls/plusls-carpet-addition) 并启用 。 目前有且仅有Fabric服务端可以安装PCA来确保同步，其他类型服务端没有支持计划。`pcaSyncProtocol`
PCA在客户端要添加吗？
