### ISSUE TITLE
[Bug] 服务器渲染村民转换时间不实时刷新

### ISSUE THREAD

**Issue by heyibear** [plusls/MasaGadget#56]
### Question Type

Others

### Description

服务器已开启PCA指令，渲染村民转换时间或者补货时间都不会实时变化，需要设置PCA同步快捷键后每次都要手动按一次才会刷新，有点麻烦，请问可以弄成实时刷新吗，其他的都正常，包括容器显示，容器内物品改变也会实时显示

**Comment by Kiten-bo** [comment]
游戏版本：1.19.2
PCA版本：最新版
MasaGadget版本：最新版
