### ISSUE TITLE
[Bug] G+C无法打开配置界面

### ISSUE THREAD

**Issue by swe3per** [plusls/MasaGadget#57]
### Minecraft Version

1.19.2

### MasaGadget Version

3.0

### Description

G+C无法唤起配置界面，G和C键都没有冲突
modmenu中能看到已加载，但config目录中也没有生成masa_gadget的配置文件，用PCL2重新下载安装了一个全新的1.19.2，前置如下：
malilib-fabric-1.19.2-0.13.0
magiclib-0.5.37
mod版本如下：MasaGadget-3.0.0
启动游戏后还是无法唤醒，也是config目录中没有生成

### To Reproduce

G+C无法唤起配置界面，G和C键都没有冲突
modmenu中能看到已加载，但config目录中也没有生成masa_gadget的配置文件，用PCL2重新下载安装了一个全新的1.19.2，前置如下：
malilib-fabric-1.19.2-0.13.0
magiclib-0.5.37
mod版本如下：MasaGadget-3.0.0
启动游戏后还是无法唤醒，也是config目录中没有生成

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by stevened7246** [comment]
> ### Minecraft Version
> 1.19.2
> 
> ### MasaGadget Version
> 3.0
> 
> ### Description
> G+C无法唤起配置界面，G和C键都没有冲突 modmenu中能看到已加载，但config目录中也没有生成masa_gadget的配置文件，用PCL2重新下载安装了一个全新的1.19.2，前置如下： malilib-fabric-1.19.2-0.13.0 magiclib-0.5.37 mod版本如下：MasaGadget-3.0.0 启动游戏后还是无法唤醒，也是config目录中没有生成
> 
> ### To Reproduce
> G+C无法唤起配置界面，G和C键都没有冲突 modmenu中能看到已加载，但config目录中也没有生成masa_gadget的配置文件，用PCL2重新下载安装了一个全新的1.19.2，前置如下： malilib-fabric-1.19.2-0.13.0 magiclib-0.5.37 mod版本如下：MasaGadget-3.0.0 启动游戏后还是无法唤醒，也是config目录中没有生成
> 
> ### Expected behavior
> _No response_
> 
> ### Log
> _No response_
> 
> ### Latest CI build tested
> * [x]  I confirm that this problem still exists with the latest CI build.

可以去Actions页面下载最新版本
