### ISSUE TITLE
[Feature Request] 更新到1.19以上的版本

### ISSUE THREAD

**Issue by SilianZ** [plusls/MasaGadget#61]
### What new features do you want?

[Feature Request] 更新到1.19以上的版本

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Hendrix-Shen** [comment]
https://hendrixshen.lanzouy.com/b0c4srcti密码:plusls
此处提供模组仅适用于 1.19.2
