### ISSUE TITLE
[Feature Request] Update to 1.19.3

### ISSUE THREAD

**Issue by Notoriousi** [plusls/MasaGadget#63]
### What new features do you want?

MasaGadget is incompatible with 1.19.3

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Hendrix-Shen** [comment]
Try this version: [3.0.0-beta+f5856ee](https://github.com/plusls/MasaGadget/suites/9854389287/artifacts/475126756).

**Comment by Notoriousi** [comment]
Works perfectly
