### ISSUE TITLE
[Bug] 1.19.3 无法打开设置（游戏中和mod菜单中均不行）

### ISSUE THREAD

**Issue by unbadfish** [plusls/MasaGadget#65]
### Minecraft Version

1.19.3

### MasaGadget Version

f5856ee

### Description

1. 在https://github.com/plusls/MasaGadget/actions/runs/3691718750 下载的本体
2. 在https://github.com/Hendrix-Shen/MagicLib/releases/tag/dev%2F0.7.267 下载的1.19.3版magiclib，MagicLib-1.19.3-0.7.267.209+e1d03ba-beta
3. 其他模组版本：carpet-1.19.3-1.4.93+v221230，fabric-api-0.70.0+1.19.3
4. 游戏中按`G+C`无法显示菜单，模组界面无法设置
![Snipaste_2023-01-27_11-53-32](https://user-images.githubusercontent.com/61961263/215006789-ae2d6d64-f8a0-4385-bcba-6f7f5c741795.png)

### To Reproduce

无论是否安装地毯模组（carpet-1.19.3-1.4.93+v221230），均会产生bug

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
MagicLib 处于实验阶段，请回退值0.6.x。

**Comment by unbadfish** [comment]
谢谢，已成功解决（下载https://github.com/Hendrix-Shen/MagicLib/releases/download/dev%2F0.6.200/magiclib-0.6.200+a47eb26-beta.jar ），建议添加描述至文档中
建议：应下载magiclib-0.6.xyz+abcdedf-beta.jar，不要下载magiclib-1.1x.y-0.6.xyz+abcdedf-beta.jar，好像识别不了
