### ISSUE TITLE
[Bug] 真的修了tickwarp卡了的问题么

### ISSUE THREAD

**Issue by roj234** [plusls/MasaGadget#67]
### Minecraft Version

1.19.2

### MasaGadget Version

从modrinth下的3.0.1

### Description

如下，然后用VisualVM追踪到了那个函数，看commit你在3.0.1有修改
![Visual VM](https://i2.100024.xyz/2023/02/02/me5ylu.webp)
不是说tick wrap的问题修了么，是否上传的文件的确和文件名一样是3.0.0
或者这是新的bug

### To Reproduce

/gamerule randomTickSpeed 100000
然后准星指向任意方块

### Expected behavior

FPS不下降到0

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by roj234** [comment]
cc10e14可以复现

**Comment by Fiz-Victor** [comment]
不考虑优化一下吗，1.20.1成功复现
![image](https://github.com/plusls/MasaGadget/assets/62250232/d51ffa73-a2c1-4df9-b699-91756bad8f92)

**Comment by Hendrix-Shen** [comment]
是否尝试过启用 `容器预览时使用缓存(inventoryPreviewUseCache)` 选项？

**Comment by Fiz-Victor** [comment]
关了，看代码ClientTick的末尾会无视任何设置遍历所有世界里的容器然后把游戏给弄得很卡

**Comment by roj234** [comment]
getChunk在单人下会和本地服务端同步区块，如果本地服务端的TPS小于20客户端的tick就会等服务端赶上
PS: mixin掉！![doge](https://user-images.githubusercontent.com/82699138/230711540-a196d7a3-f29f-418b-8dff-d03afb1505c5.png)
