### ISSUE TITLE
[Feature Request] update to 1.19.3 pls

### ISSUE THREAD

**Issue by Pi3tro88** [plusls/MasaGadget#68]
### What new features do you want?

 thats it lmao

### Latest CI build tested

- [x] I confirm that the feature I requested is not in the latest CI build.

**Comment by KiritoKing** [comment]
确实 我在1.19.3安装Gadget后根本没法探测到其他的Masa Mods

**Comment by Hendrix-Shen** [comment]
Try this version [3.0.0-beta+f5856ee](https://github.com/plusls/MasaGadget/suites/9854389287/artifacts/475126756).

**Comment by KiritoKing** [comment]
> 

ok, i'll try it

**Comment by KiritoKing** [comment]
> Try this version [3.0.0-beta+f5856ee](https://github.com/plusls/MasaGadget/suites/9854389287/artifacts/475126756).

Thx, I'll try it soon.
