### ISSUE TITLE
[Feature Request] 增加村民绑定工作方块和床显示功能

### ISSUE THREAD

**Issue by s-yh-china** [plusls/MasaGadget#71]
### What new features do you want?

村民绑定工作方块日常乱套 这是一个很需要的功能

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Hendrix-Shen** [comment]
请尝试此版本：[3.2.313+03fb41f](https://github.com/plusls/MasaGadget/suites/14270809673/artifacts/801968637)
