### ISSUE TITLE
Unable to open GUI

### ISSUE THREAD

**Issue by AUNTSAMA** [plusls/MasaGadget#73]
### Question Type

Usages

### Description

This is an issue discovered in version 1.19.2
I found in Masagadget that the shortcut "G+C" doesn't work and I can't find the settings option in the mod menu either And the exact same thing happens in "oh my Minecraft client"mod I can be sure that the mod in it is complete 
In “minihud” I didn't find this to be the case
![9~UO{N1T OA@X3J5Q@9 ZKH](https://user-images.githubusercontent.com/123088748/226575877-9b382cc2-ad75-4781-bd81-4001bc5e8383.png)

**Comment by Crumbo225** [comment]
I'm having the exact same issue same version as well, any help would be much appreciated:)

**Comment by Crumbo225** [comment]
> I'm having the exact same issue same version as well, any help would be much appreciated:)

figured it out! head over to curseforge and download the latest release of the mod, the newest file works for all versions
