### ISSUE TITLE
[Bug] 游戏暂停后继续有概率FPS骤降

### ISSUE THREAD

**Issue by lry77ist** [plusls/MasaGadget#74]
### Minecraft Version

1.19.3/1.19.4

### MasaGadget Version

MasaGadget-3.1.289+1ca4352-stable.jar

### Description

在1.19.3和1.19.4中，按下esc暂停后再继续游戏有概率导致FPS骤降，尤其是准星指向某一方块时，转动视角能感受到明显卡顿，并且此卡顿会一直持续，不会随着游戏的进行而消失直到下一次甚至之后若干次暂停后。同样的问题亦有可能发生在睡觉跳过夜晚、穿过传送门之后。经排查可确认此问题由MasaGadget导致，但不确定是否是mod内某一选项开启所导致。（1.19.2中不存在这一Bug）

### To Reproduce

按下esc暂停后继续游戏、穿过传送门、睡觉、编辑告示牌、打开小地图等操作后有概率导致FPS骤降。

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
未能复现此问题。
