### ISSUE TITLE
[Question] 1.19.4服务器不能正确同步渲染第一本附魔书

### ISSUE THREAD

**Issue by joeyreg** [plusls/MasaGadget#75]
### Question Type

Usages

### Description

1.19.4
magiclib-1.19.4-0.7.293+17aa28c-stable
MasaGadget-1.19.4-3.1.289+1ca4352-stable
PluslsCarpetAddition-1.19.4-0.3.148+a6f5948-beta
客户端跟服务器都安装了这三个mod，但是村民第一本附魔书还是渲染不正确，显示的不是实际的书

**Comment by Hendrix-Shen** [comment]
PCA 是否已启用 pcaSyncProtocol 规则？

**Comment by joeyreg** [comment]
![未命名1682317040](https://user-images.githubusercontent.com/60729138/233914498-e8a8b29c-78f0-42b8-81de-f10ad50a7cc2.png)
y这个功能默认开启的吧？

**Comment by Hendrix-Shen** [comment]
指服务端PCA规则。

**Comment by miaotouy** [comment]
> 指服务端PCA规则。使用 `/pca pcaSyncProtocol true` 来启用。

我也遇到了，而且我不知道怎么获取适用于1.19.4版本的PCA模组，PCA的GitHub页面我看了有1.19.x分支，但是很久没更新了，我尝试自己构建发现并不能用于1.19.4

**Comment by Hendrix-Shen** [comment]
> > 指服务端PCA规则。使用 `/pca pcaSyncProtocol true` 来启用。
> 
> 我也遇到了，而且我不知道怎么获取适用于1.19.4版本的PCA模组，PCA的GitHub页面我看了有1.19.x分支，但是很久没更新了，我尝试自己构建发现并不能用于1.19.4

https://github.com/Nyan-Work/plusls-carpet-addition

**Comment by Pigmud** [comment]
我单人存档也有这个问题，pcaSyncProtocol开了

**Comment by TjXySky** [comment]
PCA 没有1.20.1版本😥😭
