### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TOMhongshu** [plusls/MasaGadget#76]
### Minecraft Version

1.19.2

### MasaGadget Version

MasaGadget-1.19.2-3.1.289+1ca4352-stable.jar

### Description

安装模组后打开masa配置界面就会崩溃 如：投影 迷你hud这类

### To Reproduce

打开masa配置界面就会崩溃

### Log

崩溃日志
[2023-04-29-7.log](https://github.com/plusls/MasaGadget/files/11358142/2023-04-29-7.log)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by TOMhongshu** [comment]
单人/服务器 都会崩

**Comment by Hendrix-Shen** [comment]
已知问题，安装 Mod Menu 或使用最新测试版。

**Comment by helscarthe** [comment]
> 已知问题，安装 Mod Menu 或使用最新测试版。

你好，我不懂中文，也不知道英文是否可以，所以很抱歉用机器翻译的语气。

我有基本相同的问题，只是我有Mod Menu，但它仍然不能工作。这个测试版MasaGadget在哪里，我可以测试一下？我没有看到它在发布中。

**Comment by Hendrix-Shen** [comment]
> > 已知问题，安装 Mod Menu 或使用最新测试版。
> 
> 你好，我不懂中文，也不知道英文是否可以，所以很抱歉用机器翻译的语气。
> 
> 我有基本相同的问题，只是我有Mod Menu，但它仍然不能工作。这个测试版MasaGadget在哪里，我可以测试一下？我没有看到它在发布中。
> 
> @Hendrix-Shen

Masa updated Malilib (0.15.4) for Minecraft 1.19.4, causing a minor break, related issue: #77. The problem has been solved, please try this version: [3.2.300+97348ea](https://github.com/plusls/MasaGadget/suites/12726733976/artifacts/683639957).

If you are still not working please create a new issue and provide details.
