### ISSUE TITLE
[Bug] 1.19.4版本加载modmenu和tweakermore后启动时发生崩溃

### ISSUE THREAD

**Issue by shinyashen** [plusls/MasaGadget#77]
### Minecraft Version

1.19.4

### MasaGadget Version

3.2.299+5ec84c0

### Description

在1.19.4版本中，加载最新版本的`modmenu`和`tweakermore`后游戏崩溃。测试过三个模组不同时加载的情况，均成功启动游戏。此外，使用的`malilib`也为最新版本`0.15.4`。

### To Reproduce

安装以下mod后启动游戏：
- fabric-api-0.80.0+1.19.4.jar
- magiclib-0.7.318+85c565a-beta.jar
- malilib-fabric-1.19.4-0.15.4.jar
- MasaGadget-3.2.299+5ec84c0-beta.jar
- modmenu-6.2.2.jar
- tweakermore-mc1.19.4-v3.11.1.jar

### Expected behavior

成功启动游戏。

### Log

[minecraft-exported-logs-2023-05-06T11-01-06.log](https://github.com/plusls/MasaGadget/files/11411106/minecraft-exported-logs-2023-05-06T11-01-06.log)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
尝试 [3.2.300+97348ea](https://github.com/plusls/MasaGadget/suites/12726733976/artifacts/683639957) 版本。

**Comment by shinyashen** [comment]
最新版本已可以正常启动。
