### ISSUE TITLE
[Feature Request] Support Minecraft 1.20.1   1.20.1支持！目前无法正常使用

### ISSUE THREAD

**Issue by HMwancheng** [plusls/MasaGadget#88]
### What new features do you want?

1.20.1支持！目前无法正常使用
![image](https://github.com/plusls/MasaGadget/assets/91036325/9a05f8f8-4d5d-47f3-8469-362803b0bfcb)

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Shizuku303** [comment]
难怪我试了好久都不行😂

**Comment by Livelongwer** [comment]
天，我说怎么不能用
