### ISSUE TITLE
[Bug] 右键导致游戏崩溃

### ISSUE THREAD

**Issue by MINECRAFTGUIYU** [plusls/MasaGadget#89]
### Minecraft Version

1.19.2

### MasaGadget Version

3.2.308+2c7a07f-stable

### Description

在一些服务器中右键会概率出现崩溃现象

### To Reproduce

打开Minecraft→多人游戏→添加服务器→进入服务器→右键

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by MINECRAFTGUIYU** [comment]
补充：仅在手持物品时会这样

**Comment by Hendrix-Shen** [comment]
详细日志？
