### ISSUE TITLE
村民渲染有问题

### ISSUE THREAD

**Issue by linyiyi1314** [plusls/MasaGadget#93]
### Question Type

Codes

### Description

 被杀死或者恢复都会崩溃游戏

**Comment by Hendrix-Shen** [comment]
与 #91 重复。

--------------------

Bug 反馈报到 Bug 分类，不要报到 Question 分类。
另外，GitHub Issue 是项目反馈区，不是聊天区，更不是百度贴吧，相同问题请报到同一个 issues 里面。
