### ISSUE TITLE
[Bug] 在没有PCA服务端容器预览导致放方块

### ISSUE THREAD

**Issue by acaciachan** [plusls/MasaGadget#95]
### Minecraft Version

1.20.1，可能所有版本都有这个问题

### MasaGadget Version

MasaGadget-all-3.2.311+aae0554-stable

### Description

在没有PCA同步数据服务器上使用容器预览，使用打开容器但是不显示容器界面的功能进行容器预览时，如果容器预览和shift一起按下，会导致手里的方块以20Hz的速度一直放

### To Reproduce

上述

### Expected behavior

方块不会被放下

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
尝试此版本：[3.2.314+b2cde21](https://github.com/plusls/MasaGadget/suites/14511893449/artifacts/820636906).
