### ISSUE TITLE
[Bug] 与投影模组显示的兼容性问题

### ISSUE THREAD

**Issue by wangzhijie0602** [plusls/MasaGadget#96]
### Minecraft Version

1.20.1

### MasaGadget Version

MasaGadget-all-3.2.311+aae0554-stable

### Description

当同时使用钠和投影模组并在游戏设置中将视频设置-quality-图像质量设置为极佳时
![1690347257756](https://github.com/plusls/MasaGadget/assets/46142484/60e52056-0f7f-4171-a28a-47aa2d9c5235)
，村民会无法显示“渲染村民交易的第一本附魔书”等信息
![2023-07-26_12 56 02](https://github.com/plusls/MasaGadget/assets/46142484/a66927bc-371a-4268-a81f-773822ebcdf2)
![2023-07-26_13 05 09](https://github.com/plusls/MasaGadget/assets/46142484/8359863c-da6e-47c2-80a9-470bd0dc3803)
，未安装投影时，并未发现此问题
所以我怀疑是投影的渲染和Masa Gadget有冲突，
最后，在钠的图像质量为极佳时，投影选项中的视觉-enablearea|选区边框启用切换关闭，村民的信息显示正常
![2023-07-26_13 08 55](https://github.com/plusls/MasaGadget/assets/46142484/d6164498-9d09-4735-8aeb-5459ec01d542)
以下为选项打开状态
![2023-07-26_13 08 57](https://github.com/plusls/MasaGadget/assets/46142484/e9492231-6877-47eb-b0ca-3a7767f17284)

### To Reproduce

![1690348502316](https://github.com/plusls/MasaGadget/assets/46142484/d1d078fd-584e-419b-b704-26a161b1841d)
以上为mod列表
启动游戏后在选项-视频设置-quality-图像质量设置为极佳，在单人游戏中放置村民和讲台即可，同时，将投影选项中的视觉-enablearea|选区边框启用切换设置为false，村民的显示恢复正常

其实村民并非没有显示，在复现问题后，靠近村民，紧贴村民时，会显示Masa Gadget的相关图层，但显然，这样是不正常的
![2023-07-26_13 17 36](https://github.com/plusls/MasaGadget/assets/46142484/5c2be6c5-3e9d-4163-aafb-68a34f2f12fe)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
更新一下 MagicLib：[0.7.362+2dac2a9](https://github.com/Hendrix-Shen/MagicLib/releases/download/dev%2F0.7.305/magiclib-all-0.7.362+2dac2a9-beta.jar)
