### ISSUE TITLE
[Bug] 村民工作方块显示不匹配

### ISSUE THREAD

**Issue by twcrequ1em** [plusls/MasaGadget#97]
### Minecraft Version

1.20.1

### MasaGadget Version

MasaGadget-all-3.2.314+b2cde21-beta

### Description

在个人存档中，村民的第一本附魔书显示是正确的，但是到了服务器中村民第一本附魔书显示错误，救治村民所需时间也会卡在“-1”

### To Reproduce

在刷新村民工作方块时发现显示不正确

### Expected behavior

若是服务器和单人存档运行方式有区别，请问如何让服务器的村民显示正确

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
服务器需要安装 plusls-carpet-addition 并启用 pca同步协议

**Comment by twcrequ1em** [comment]
谢谢，已经在让服主安装了。
