### ISSUE TITLE
[Bug] 容器预览快捷键和鼠标中键保存方块冲突

### ISSUE THREAD

**Issue by acaciachan** [plusls/MasaGadget#98]
### Minecraft Version

1.20.1

### MasaGadget Version

MasaGadget-all-3.2.315+1cc767c-beta.jar

### Description

按下容器预览快捷键时，指向铁轨，有个功能是穿透铁轨预览后面的容器，但是就算是铁轨后面没有容器，也会阻止鼠标中键保存方块

### To Reproduce

1

### Expected behavior

容器预览和鼠标中间保存方块块不会冲突
另外如果可以的话，穿透方块进行容器预览不只铁轨，可以考虑下加个白名单之类的添加方块

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
没理解怎么个冲突法，如果是不能穿透铁轨保存容器，这是预期行为。

**Comment by acaciachan** [comment]
没说明白，应该是按住容器预览对着铁轨，无法鼠标中键保存铁轨。即使铁轨后面没有容器也无法保存
预期应该是按住容器预览的键即使对准了铁轨预览着榕城区也能保存铁轨。
Alt这个键位置比较方便触发天天用的功能，什么容器预览，疾跑，反向放置方块啥的

**Comment by acaciachan** [comment]
等一下，刚刚又去试了试不知道为啥压不会触发了，我研究研究再遇到这个问题的时候看看怎么稳定复现吧
